version: '3.4'

services:
  crimsonlibrary:
    image: ${DOCKER_REGISTRY-}crimsonlibrary
    build:
      context: .
      dockerfile: CrimsonLibrary/Dockerfile
    container_name: CrimzonLibrary

  crimsonDatabase:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "DiLb984ImW"
      ACCEPT_EULA: "Y"
    ports:
     - "1434:1433" 
    container_name: CrimsonDatabase
    volumes:
      - "./SqlServer-db-data:/var/opt/mssql/data"


volumes: 
  db-data: